USE [master]
GO

/****** Object:  Database [FinalWorkshopDB]    Script Date: 14-Sep-18 22:36:47 ******/
CREATE DATABASE [FinalWorkshopDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FinalWorkshopDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FinalWorkshopDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FinalWorkshopDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FinalWorkshopDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FinalWorkshopDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FinalWorkshopDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FinalWorkshopDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FinalWorkshopDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FinalWorkshopDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FinalWorkshopDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FinalWorkshopDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FinalWorkshopDB] SET  MULTI_USER 
GO

ALTER DATABASE [FinalWorkshopDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FinalWorkshopDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FinalWorkshopDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FinalWorkshopDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FinalWorkshopDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FinalWorkshopDB] SET QUERY_STORE = OFF
GO

USE [FinalWorkshopDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [FinalWorkshopDB] SET  READ_WRITE 
GO


